### ISSUE TITLE
Still valid?

### ISSUE THREAD

**Issue by borrrden** [sqlcipher/sqlcipher-tools#1]
I know this is for version 1, but I tweaked it to use the raw key material that I have and the resulting database has bits and pieces of the correct unencrypted database in it but overall it is corrupt with incorrectly decrypted data and large swaths of NULL.  How can I change it further to get the correct result?

**Comment by sjlombardo** [comment]
@borrrden what version of SQLCipher database are you trying to decrypt? Are you using all the defaults SQLCipher pragmas in terms of page size, HMAC, etc?

**Comment by borrrden** [comment]
Page size is the default (1024).  That's something I checked.  The derivation rounds are 64000, but it doesn't matter because I am using raw keys on the database so I have the key material already (I changed the program to not derive the key and instead just use the hex value I provide).  It looks to be close as I can see some of the schema in plaintext, but I'm just wondering if there are any quirks between v1 and v3 (the version of database I have), like the IV changing location or the lack of salt when using raw keys, etc.  I didn't touch any of the pragmas when making the DB and using the sqlcipher command line tool reads it alright.

The reason I need this is, ironically, there is a small sqlite level corruption in the database and I wanted to examine the unencrypted file.  SQLCipher cannot decrypt it because it will see the corruption and throw an error (Database malformed) so I was analyzing the source code to sqlcipher when I found this tool.

**Comment by sjlombardo** [comment]
@borrrden I suspect that the problem here is that the page layout between version 1 and version 3 has changed slightly, given the introduction of the per-page MAC. Specifically, the reserve size for each page is larger in the new version, which would affect decryption. I just pushed out a quick update which should allow decrypt.c to work with the newer format. Let me know if that works for you.

**Comment by borrrden** [comment]
I didn't realize you commented and I was looking at it again thinking "how did I miss that?".  I was writing a C# version for my own purposes and I noticed I needed to account for the MAC so I started guessing values that seemed right until one value spit out a valid SQLite3 header. It still isn't fully right, but I tried out your version again and it worked fine, thanks for the quick response!
